<?php
$this->headTitle($this->_('Access denied', 'Acl'));
?>

<div class="container">
    <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h3 class="panel-title"><?= $this->_('Access denied', 'Acl'); ?></h3>
                </div>

                <div class="panel-body"><p><?= $this->_('You are not allowed to access this page', 'Acl'); ?></p></div>
            </div>
        </div>
    </div>
</div>
