<?php
$this->headTitle($this->_('Change password'));
?>

<?php $this->placeHolder('nav')->captureStart(); ?>
<ul>
    <li><a href="<?= $this->url('user\profile\password'); ?>" title="<?= $this->_('Password', 'User'); ?>"><?= $this->_('Change password'); ?></a></li>
</ul>
<?php $this->placeHolder('nav')->captureEnd(); ?>

<div class="container">
    <?= $this->flashMessenger(); ?>

    <p><?= $this->_('The password should have upper, lower, special, and number characters'); ?></p>

    <form class="form-horizontal" action="<?= $this->url('user\profile\password'); ?>" method="post">
        <div class="form-group">
            <label class="col-lg-4 control-label"><?= $this->_('Current password'); ?></label>
            <div class="col-lg-4">
                <input type="password" name="password" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-4 control-label"><?= $this->_('New password'); ?></label>
            <div class="col-lg-4">
                <input type="password" name="new_password" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <label class="col-lg-4 control-label"><?= $this->_('Retype password'); ?></label>
            <div class="col-lg-4">
                <input type="password" name="retype_password" class="form-control" />
            </div>
        </div>

        <hr>

        <div class="form-group">
            <div class="col-lg-8 col-lg-offset-4">
                <button type="submit" class="btn btn-primary"><?= $this->_('Save'); ?></button>
            </div>
        </div>
    </form>
</div>
