<div class="form-group">
    <label class="col-lg-2 control-label"><?= $this->_('Country'); ?></label>
    <div class="col-lg-3">
        <select name="country" class="form-control">
        <?php foreach($this->countries as $code => $name) : ?>
            <option value="<?= $code; ?>" <?php if ($code == $this->address['country']) : ?>selected<?php endif; ?>><?= $name; ?></option>
        <?php endforeach; ?>
        </select>
    </div>
</div>

<div class="form-group">
    <label class="col-lg-2 control-label"><?= $this->_('Street'); ?></label>
    <div class="col-lg-4">
        <input type="text" name="street1" class="form-control" value="<?= $this->escapeHtml($this->address['street1']); ?>" placeholder="<?= $this->_('Street line 1'); ?>" />
    </div>
</div>

<div class="form-group">
    <div class="col-lg-4 col-lg-offset-2">
        <input type="text" name="street2" class="form-control" value="<?= $this->escapeHtml($this->address['street2']); ?>" placeholder="<?= $this->_('Street line 2'); ?>" />
    </div>
</div>

<div class="form-group">
    <label class="col-lg-2 control-label"><?= $this->_('City'); ?></label>
    <div class="col-lg-3">
        <input type="text" name="city" class="form-control" value="<?= $this->escapeHtml($this->address['city']); ?>" />
    </div>
</div>

<div class="form-group">
    <label class="col-lg-2 control-label"><?= $this->_('State/Province'); ?></label>
    <div class="col-lg-3">
        <input type="text" name="state" data-country="" class="form-control" value="<?= $this->escapeHtml($this->address['state']); ?>" />
        <select name="state" data-country="US" class="form-control hide" disabled>
            <?php foreach ($this->usStates as $code => $name) : ?>
                <option value="<?= $code; ?>" <?php if ($code == $this->address['state']) : ?>selected<?php endif; ?>><?= $name; ?></option>
            <?php endforeach; ?>
        </select>
        <select name="state" data-country="CA" class="form-control hide" disabled>
            <?php foreach ($this->canadaProvinces as $code => $name) : ?>
                <option value="<?= $code; ?>" <?php if ($code == $this->address['state']) : ?>selected<?php endif; ?>><?= $name; ?></option>
            <?php endforeach; ?>
        </select>
    </div>
</div>

<div class="form-group">
    <label class="col-lg-2 control-label"><?= $this->_('Zip code'); ?></label>
    <div class="col-lg-3">
        <input type="text" name="zip_code" class="form-control" value="<?= $this->escapeHtml($this->address['zip_code']); ?>" />
    </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
    // Show the US states or Canada provinces when user choose one of these countries
    $('select[name="country"]').on('change', function() {
        var country = $(this).val();
        if (['US', 'CA'].indexOf(country) == -1) {
            country = '';
        }
        $('[name="state"]').removeClass('show').addClass('hide').attr('disabled', 'disabled')
                           .filter('[data-country="' + country + '"]').addClass('show').removeAttr('disabled');
    });
});
</script>
